# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI/DialogJoin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgJoin(object):
    def setupUi(self, DlgJoin):
        DlgJoin.setObjectName("DlgJoin")
        DlgJoin.setWindowModality(QtCore.Qt.NonModal)
        DlgJoin.resize(422, 454)
        DlgJoin.setMinimumSize(QtCore.QSize(300, 300))
        DlgJoin.setStyleSheet("QWidget{\n"
"background-color:rgb(196, 215, 178);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color:white;\n"
"border:1px solid rgb(196, 215, 178);\n"
"border-radius:5px;\n"
"padding:5px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color:white;\n"
"border:1px solid rgb(196, 215, 178);\n"
"border-radius:5px;\n"
"padding:5px;\n"
"min-height:25px;\n"
"}")
        DlgJoin.setModal(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DlgJoin)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(DlgJoin)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_close = QtWidgets.QPushButton(self.widget)
        self.btn_close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Image/img_close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon)
        self.btn_close.setAutoDefault(False)
        self.btn_close.setFlat(True)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout.addWidget(self.btn_close)
        self.verticalLayout_2.addWidget(self.widget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(DlgJoin)
        font = QtGui.QFont()
        font.setFamily("ONE 모바일POP")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.edt_email = QtWidgets.QLineEdit(DlgJoin)
        self.edt_email.setObjectName("edt_email")
        self.horizontalLayout_2.addWidget(self.edt_email)
        self.btn_check = QtWidgets.QPushButton(DlgJoin)
        self.btn_check.setObjectName("btn_check")
        self.horizontalLayout_2.addWidget(self.btn_check)
        self.horizontalLayout_2.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.edt_pwd_1 = QtWidgets.QLineEdit(DlgJoin)
        self.edt_pwd_1.setObjectName("edt_pwd_1")
        self.verticalLayout.addWidget(self.edt_pwd_1)
        self.edt_pwd_2 = QtWidgets.QLineEdit(DlgJoin)
        self.edt_pwd_2.setObjectName("edt_pwd_2")
        self.verticalLayout.addWidget(self.edt_pwd_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.btn_join = QtWidgets.QPushButton(DlgJoin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_join.sizePolicy().hasHeightForWidth())
        self.btn_join.setSizePolicy(sizePolicy)
        self.btn_join.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_join.setFont(font)
        self.btn_join.setStyleSheet("")
        self.btn_join.setObjectName("btn_join")
        self.verticalLayout.addWidget(self.btn_join)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.setStretch(1, 1)

        self.retranslateUi(DlgJoin)
        QtCore.QMetaObject.connectSlotsByName(DlgJoin)

    def retranslateUi(self, DlgJoin):
        _translate = QtCore.QCoreApplication.translate
        DlgJoin.setWindowTitle(_translate("DlgJoin", "회원가입"))
        self.label.setText(_translate("DlgJoin", "회원가입"))
        self.edt_email.setPlaceholderText(_translate("DlgJoin", "이메일주소"))
        self.btn_check.setText(_translate("DlgJoin", "중복\n"
"확인"))
        self.edt_pwd_1.setPlaceholderText(_translate("DlgJoin", "비밀번호"))
        self.edt_pwd_2.setPlaceholderText(_translate("DlgJoin", "비밀번호 확인"))
        self.btn_join.setText(_translate("DlgJoin", "회원가입"))
