
path: D:\CropFairy\AI\pepper  # dataset root dir
train: images\train2  # train images (relative to 'path')
val: images\test  # val images (relative to 'path')

# Classes
names: ['00', '01', '103', '104', '203', '206', '207', '208']
nc: 8
